name: Fetch HTML from Google Drive
permissions:
  contents: write
on:
  schedule:
    - cron: '*/5 * * * *'   # Runs every 5 minutes
  workflow_dispatch:

jobs:
  fetch-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download HTML from Google Drive
      run: |
        curl -L -o Automation500.html "https://drive.google.com/uc?export=download&id=1uTOl4e3FQ6vQBveY-QiFpV1xbZKXEhG8"

    - name: Commit and push if changed
    with:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add Automation500.html
        git diff --cached --quiet || git commit -m "Auto update HTML from Google Drive"
        git push
